
<!--Incase you don't want real time updates to the live chat plugin when options are changed, use the below code snippet. Please note that each time you change the settings you will need to copy and paste the snippet code to your website--> 
<call-us 
phonesystem-url="https://budgetphp.pa.3cx.us" 
style="position:fixed;font-family: Arial;z-index: 99999;--call-us-form-header-background:#ff523d;--call-us-main-button-background:#0071bd;--call-us-client-text-color:#d4d4d4;--call-us-agent-text-color:#eeeeee;--call-us-form-height:28.5vh;right: 20px; bottom: 50px;" 
id="wp-live-chat-by-3CX" 
minimized="true" 
animation-style="noanimation" 
party="LiveChat965313" 
minimized-style="BubbleRight" 
allow-call="true" 
allow-video="false" 
allow-soundnotifications="true" 
enable-mute="true" 
enable-onmobile="true" 
offline-enabled="true" 
enable="true" 
ignore-queueownership="false" 
authentication="both" 
show-operator-actual-name="true" 
channel="phone" 
aknowledge-received="true" 
gdpr-enabled="false" 
message-userinfo-format="both" 
message-dateformat="both" 
lang="browser" 
button-icon-type="default" 
greeting-visibility="none" 
greeting-offline-visibility="none" 
chat-delay="2000" 
enable-direct-call="true" 
enable-ga="false" 
></call-us>
<script defer src="https://downloads-global.3cx.com/downloads/livechatandtalk/v1/callus.js" id="tcx-callus-js"></script>